"""Config generation for `draindeck init` (doc 16 §4 step 6). Renders
`config.local.yaml` as hand-written text — so per-line `# TODO:` comments
can sit next to the exact value they qualify, matching the existing
`config.local.yaml`/`config.example.yaml` style — while delegating every
interpolated scalar's YAML quoting/escaping to PyYAML rather than
hand-rolling it. No new schema keys are introduced anywhere; comments are
inert to `yaml.safe_load`/`load_config()` by construction.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml

from .detect import CommandProposal, DetectionRow


def _scalar(value: str) -> str:
    """A single YAML scalar, correctly quoted/escaped for embedding in a
    hand-written template line. Never hand-roll YAML quoting rules —
    always delegate to PyYAML. Dumping the bare value directly
    (``yaml.safe_dump(value, ...)``) is unsafe: PyYAML appends an
    explicit ``...`` document-end marker after a PLAIN top-level scalar
    (verified empirically this session — e.g. ``yaml.safe_dump("my
    file.js", default_flow_style=True)`` returns ``"my file.js\\n...\\n"``),
    which ``.strip()`` does NOT remove (``...`` is not whitespace) and
    which would corrupt the surrounding structure when spliced inline.
    Wrapping the value in a one-key mapping sidesteps this entirely —
    mappings never get the document-end marker — then the ``key: ``
    prefix is stripped back off. Verified to round-trip through
    ``yaml.safe_load`` for plain, space-containing, backslash-containing,
    and colon-containing values alike.

    ``width=float("inf")`` is required: PyYAML's default 80-column width
    line-folds a long plain scalar across multiple lines (verified
    empirically this session — a long Windows path was split mid-string
    with a continuation line indented relative to the wrapping mapping,
    not to the caller's own template indentation, corrupting the
    surrounding structure). Disabling folding keeps every value on the
    single line the template expects.
    """
    dumped = yaml.safe_dump(
        {"x": value}, default_flow_style=False, width=float("inf")
    )
    return dumped[len("x: "):].rstrip("\n")


_RULE2_COMMENT = (
    "    # TODO: confirm — ADR-23 rule 2 (doc 08 §5d): this is bare\n"
    "    # pytest discovery, not explicit file targets. Narrow it to\n"
    "    # the exact test file(s) before relying on it unattended.\n"
)


def render_config(
    *,
    repo_path: Path,
    branch: str,
    branch_tip: str,
    all_matches: list[DetectionRow],
    chosen_stack: str,
    chosen: CommandProposal,
) -> str:
    """Full `config.local.yaml` text (no disk I/O — see `write_config`).
    Schema-identical to what `load_config` already parses: every key
    below exists in `Config`/`ProjectCfg`/`ValidationCfg`/etc. today, none
    are new (doc 16 §2 — Issue A never touches the schema). `engine`/
    `reviewer`/`budget`/`experiment`/`billing` are generic defaults
    mirroring `config.example.yaml` verbatim (not stack-detected — there
    is nothing in the repo to detect them from), flagged for review.
    """
    commands_yaml = "\n".join(f"      - {_scalar(c)}" for c in chosen.commands)
    other = [row.stack for row in all_matches if row.stack != chosen_stack]
    other_comment = (
        f"# Also detected: {', '.join(other)} — see the priority table in\n"
        f"# docs/16-draindeck-init-spec.md §5 to switch."
        if other else "# No other stack markers detected."
    )
    rule2_comment = _RULE2_COMMENT if chosen.needs_rule2_confirm else ""

    return f"""\
# Generated by `draindeck init` (docs/16-draindeck-init-spec.md).
# Detected stack: {chosen_stack} — review every # TODO before a real run.
{other_comment}
project:
  name: {_scalar(repo_path.name)}
  repository: {_scalar(str(repo_path))}
  branch: {_scalar(branch)}
  issues_file: Issues.md
  validation:
    # TODO: confirm — this command was proposed by stack detection, not
    # verified against your test suite. Edit before a real run if needed.
    commands:
{commands_yaml}
{rule2_comment}    timeout_seconds: 600
# The sections below are generic defaults (matching config.example.yaml),
# not detected from this repository — review before a real run.
engine:
  provider: claude-headless
  auth_mode: subscription
  model: default
reviewer:
  provider: qwen
  qwen:
    endpoint: 'http://localhost:11434'
    model: qwen2.5-coder
budget:
  max_attempts_per_issue: 3
  max_executions_per_run: 10
  hard_stop_proxy_cost_per_run_usd: 15.0
experiment:
  sample_size: 20
  attempt1_success_min: 0.30
  cost_per_shipped_issue_max_usd: 3.0
billing:
  posture: pro_subscription_headless
  headless_split_status: paused
  verified_on: {_scalar("TODO: confirm")}
  reverify_at: phase-2-gate
"""


def write_config(path: Path, text: str) -> None:
    """The only disk-write entry point in this feature (doc 16 §4 step
    6). Callers decide *whether* to call this (preflight/confirm already
    passed); this function never decides on its own."""
    path.write_text(text, encoding="utf-8")
